name: Deploy via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/deploy_key
          ${{ secrets.LXC_SSH_KEY }}
          EOF
      - name: Setup SSH local key
        run: |
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/broadcast_prd
          ${{ secrets.BROADCAST_PRD }}
          EOF
          chmod 600 ~/.ssh/broadcast_prd
      - name: Setup get deploy_key
        run: |          
          chmod 600 ~/.ssh/deploy_key
          mkdir -p ~/.cloudflared
          cat <<EOF > ~/.cloudflared/ssh.coding-stream.com-628260655058221560742c188d108f73173c950ac7d49b5322429ea25ef888b2-token
          ${{ secrets.ACCESS_TOKEN }}
          EOF
          chmod 600 ~/.cloudflared/ssh.coding-stream.com-628260655058221560742c188d108f73173c950ac7d49b5322429ea25ef888b2-token
      - name: Setup get ssh/config
        run: |          
          cat <<EOF > ~/.ssh/config
          Host gateway-via-cloudflare
            HostName ssh.coding-stream.com
            User gateway
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
            ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h

          Host browser-broadcast-websocket-prd
            HostName 192.168.11.35
            User okura
            IdentityFile ~/.ssh/broadcast_prd
            ProxyJump gateway-via-cloudflare
            StrictHostKeyChecking no
          EOF
      - name: Check token file
        run: |
          echo "==== List cloudflared token ===="
          ls -l ~/.cloudflared
          echo "==== Print token file ===="
          cat ~/.cloudflared/ssh.coding-stream.com-628260655058221560742c188d108f73173c950ac7d49b5322429ea25ef888b2-token
      - name: Run SSH
        run: ssh browser-broadcast-websocket-prd 'bash ~/broadcast-ws/infra-deploy/deploy.sh'

